[systematics.flux]
columns = ['Uncertainty', 'Type']
[systematics.flux.entries]
expskin_Flux = ['Skin Depth', 'Beam line']
horncurrent_Flux = ['Horn Current', 'Beam line']
piplus_Flux = ['$\pi^+$', 'Hadron Production']
piminus_Flux = ['$\pi^-$', 'Hadron Production']
kplus_Flux = ['$K^+$', 'Hadron Production']
kminus_Flux = ['$K^-$', 'Hadron Production']
kzero_Flux = ['$K^0_L$', 'Hadron Production']
nucleoninexsec_Flux = ['Nucleon Inelastic', 'Beam line']
nucleonqexsec_Flux = ['Nucleon QE', 'Beam line']
nucleontotxsec_Flux = ['Nucleon Total', 'Beam line']
pioninexsec_Flux = ['$\pi$ Inelastic', 'Beam line']
pionqexsec_Flux = ['$\pi$ QE', 'Beam line']
piontotxsec_Flux = ['$\pi$ Total', 'Beam line']
pot = ['POT', 'Beam line']
flux = ['Total Flux', '']

[systematics.crosssection]
columns = ['Uncertainty', 'Description']
[systematics.crosssection.entries]
GENIEReWeight_ICARUS_v2_multisim_ZExpAVariationResponse = ['ZExpAVariationResponse', 'Z-expansion description of the axial-vector form factor on CC-QE']
GENIEReWeight_ICARUS_v2_multisim_RPA_CCQE = ['RPA CCQE', 'RPA suppression of CC-QE']
GENIEReWeight_ICARUS_v2_multisim_CoulombCCQE = ['Coulomb CCQE', 'The strength of the electromagnetic potential for the Coulomb corrections on CC-QE']
GENIEReWeight_ICARUS_v2_multisim_NormCCMEC = ['Norm CCMEC', 'Normalization of CC-MEC']
GENIEReWeight_ICARUS_v2_multisim_NormNCMEC = ['Norm NCMEC', 'Normalization of NC-MEC']
GENIEReWeight_ICARUS_v2_multisim_NCELVariationResponse = ['NCEL Variation Response', 'Variation of the dipole form factor on NCEL']
GENIEReWeight_ICARUS_v2_multisim_CCRESVariationResponse = ['CCRES Variation Response', 'Variation of the dipole form factor on CC-RES']
GENIEReWeight_ICARUS_v2_multisim_NCRESVariationResponse = ['NCRES Variation Response', 'Variation of the dipole form factor on NC-RES']
GENIEReWeight_ICARUS_v2_multisim_NonRESBGvpCC1pi = ['NonRESBGvpCC1pi', 'Scale factor for the non-resonant background level of $\nu$-p CC + 1$\pi$']
GENIEReWeight_ICARUS_v2_multisim_NonRESBGvpCC2pi = ['NonRESBGvpCC2pi', 'Scale factor for the non-resonant background level of $\nu$-p CC + 2$\pi$']
GENIEReWeight_ICARUS_v2_multisim_NonRESBGvpNC1pi = ['NonRESBGvpNC1pi', 'Scale factor for the non-resonant background level of $\nu$-p NC + 1$\pi$']
GENIEReWeight_ICARUS_v2_multisim_NonRESBGvpNC2pi = ['NonRESBGvpNC2pi', 'Scale factor for the non-resonant background level of $\nu$-p NC + 2$\pi$']
GENIEReWeight_ICARUS_v2_multisim_NonRESBGvnCC1pi = ['NonRESBGvnCC1pi', 'Scale factor for the non-resonant background level of $\nu$-n CC + 1$\pi$']
GENIEReWeight_ICARUS_v2_multisim_NonRESBGvnCC2pi = ['NonRESBGvnCC2pi', 'Scale factor for the non-resonant background level of $\nu$-n CC + 2$\pi$']
GENIEReWeight_ICARUS_v2_multisim_NonRESBGvnNC1pi = ['NonRESBGvnNC1pi', 'Scale factor for the non-resonant background level of $\nu$-n NC + 1$\pi$']
GENIEReWeight_ICARUS_v2_multisim_NonRESBGvnNC2pi = ['NonRESBGvnNC2pi', 'Scale factor for the non-resonant background level of $\nu$-n NC + 2$\pi$']
GENIEReWeight_ICARUS_v2_multisim_NonRESBGvbarpCC1pi = ['NonRESBGvbarpCC1pi', 'Scale factor for the non-resonant background level of $\bar{\nu}$-p CC + 1$\pi$']
GENIEReWeight_ICARUS_v2_multisim_NonRESBGvbarpCC2pi = ['NonRESBGvbarpCC2pi', 'Scale factor for the non-resonant background level of $\bar{\nu}$-p CC + 2$\pi$']
GENIEReWeight_ICARUS_v2_multisim_NonRESBGvbarpNC1pi = ['NonRESBGvbarpNC1pi', 'Scale factor for the non-resonant background level of $\bar{\nu}$-p NC + 1$\pi$']
GENIEReWeight_ICARUS_v2_multisim_NonRESBGvbarpNC2pi = ['NonRESBGvbarpNC2pi', 'Scale factor for the non-resonant background level of $\bar{\nu}$-p NC + 2$\pi$']
GENIEReWeight_ICARUS_v2_multisim_NonRESBGvbarnCC1pi = ['NonRESBGvbarnCC1pi', 'Scale factor for the non-resonant background level of $\bar{\nu}$-n CC + 1$\pi$']
GENIEReWeight_ICARUS_v2_multisim_NonRESBGvbarnCC2pi = ['NonRESBGvbarnCC2pi', 'Scale factor for the non-resonant background level of $\bar{\nu}$-n CC + 2$\pi$']
GENIEReWeight_ICARUS_v2_multisim_NonRESBGvbarnNC1pi = ['NonRESBGvbarnNC1pi', 'Scale factor for the non-resonant background level of $\bar{\nu}$-n NC + 1$\pi$']
GENIEReWeight_ICARUS_v2_multisim_NonRESBGvbarnNC2pi = ['NonRESBGvbarnNC2pi', 'Scale factor for the non-resonant background level of $\bar{\nu}$-n NC + 2$\pi$']
GENIEReWeight_ICARUS_v2_multisim_RDecBR1gamma = ['RDecBR1gamma', 'Scale factor for the branching fraction of X + 1$\gamma$']
GENIEReWeight_ICARUS_v2_multisim_RDecBR1eta = ['RDecBR1eta', 'Scale factor for the branching fraction of X + 1$\eta$']
GENIEReWeight_ICARUS_v2_multisim_COHVariationResponse = ['COH Variation Response', 'Normalization of the Coherent production process']
GENIEReWeight_ICARUS_v2_multisim_DISBYVariationResponse = ['DISBY Variation Response', 'Normalization of the BY model of the DIS process']
GENIEReWeight_ICARUS_v2_multisim_FSI_pi_VariationResponse = ['FSI $\pi$ Variation Response', 'Variation for FSI involving pions']
GENIEReWeight_ICARUS_v2_multisim_FSI_N_VariationResponse = ['FSI N Variation Response', 'Variation for FSI involving nucleons']
genie = ['Total Cross Section', '']

[systematics.detector]
columns = ['Uncertainty', 'Type']
[systematics.detector.entries]
#tpcuntunedsigshape = ['TPC Signal Shape', 'TPC']
tpcind1increasegain = ['Increased Front Induction Gain', 'TPC']
tpcind1decreasegain = ['Decreased Front Induction Gain', 'TPC']
pmtdecreasedqe = ['PMT Quantum Efficiency', 'PMT']
ellipsoidarecomb = ['Ellipsoidal Recombination', 'TPC']
tpccohnoisep1sigma = ['Increased Coherent Noise', 'TPC']
tpcintnoisep1sigma = ['Increased Intrinsic Noise', 'TPC']
tpccohnoisem1sigma = ['Decreased Coherent Noise', 'TPC']
tpcintnoisem1sigma = ['Decreased Intrinsic Noise', 'TPC']
null = ['Null', 'None']
detector = ['Total Detector', '']

[systematics.overall]
columns = ['Uncertainty', 'Description']
[systematics.overall.entries]
detector = ['Detector', 'Uncertainties related to the modeling of the detector response']
flux = ['Flux', 'Uncertainties related to the modeling of the neutrino flux']
genie = ['Cross Section', 'Uncertainties related to neutrino interaction modeling']
statistical = ['Statistical', 'Statistical uncertainties associated with the Monte Carlo simulation sample']
offbeamstats = ['Off-beam Statistical', 'Statistical uncertainties associated with the off-beam sample used to estimate cosmic backgrounds']
total = ['Total', '']